web/router.ex
defmodule Odfi.Router do
  use Odfi.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Odfi do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/propositions", PropositionController do
      resources "/options", OptionController
    end
    resources "/votes", VoteController

  end

  # Other scopes may use custom stacks.
  scope "/api", Odfi do
    pipe_through :api
    get "/propositions", PropositionController, :propositions
    get "/results/:id", VoteController, :results
    post "/vote", VoteController, :vote
  end
end

web/models/option.ex
defmodule Odfi.Option do
  use Odfi.Web, :model

  @derive {Poison.Encoder, only: [:name]}
  schema "options" do
    field :name, :string
    belongs_to :proposition, Odfi.Proposition
    has_many :votes, Odfi.Vote

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :proposition_id])
    |> foreign_key_constraint(:proposition_id)
    |> validate_required([:name, :proposition_id])
  end
end

web/controllers/option_controller.ex
defmodule Odfi.OptionController do
  use Odfi.Web, :controller

  alias Odfi.Option

  plug :assign_proposition

  def index(conn, _params) do
    options = Repo.all(assoc(conn.assigns[:proposition], :options))
    render(conn, "index.html", options: options)
  end

  def new(conn, _params) do
    changeset =
      conn.assigns[:proposition]
      |> build_assoc(:options)
      |> Option.changeset()
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"option" => option_params}) do
    changeset =
      conn.assigns[:proposition]
      |> build_assoc(:options)
      |> Option.changeset(option_params)

    case Repo.insert(changeset) do
      {:ok, _option} ->
        conn
        |> put_flash(:info, "Option created successfully.")
        |> redirect(to: proposition_option_path(conn, :index, conn.assigns[:proposition]))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    option = Repo.get!(assoc(conn.assigns[:proposition], :options), id)
    render(conn, "show.html", option: option)
  end

  def edit(conn, %{"id" => id}) do
    option = Repo.get!(assoc(conn.assigns[:proposition], :options), id)
    changeset = Option.changeset(option)
    render(conn, "edit.html", option: option, changeset: changeset)
  end

  def update(conn, %{"id" => id, "option" => option_params}) do
    option = Repo.get!(assoc(conn.assigns[:proposition], :options), id)
    changeset = Option.changeset(option, option_params)

    case Repo.update(changeset) do
      {:ok, option} ->
        conn
        |> put_flash(:info, "Option updated successfully.")
        |> redirect(to: proposition_option_path(conn, :show, conn.assigns[:proposition], option))
      {:error, changeset} ->
        render(conn, "edit.html", option: option, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    option = Repo.get!(assoc(conn.assigns[:proposition], :options), id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(option)

    conn
    |> put_flash(:info, "Option deleted successfully.")
    |> redirect(to: proposition_option_path(conn, :index, conn.assigns[:proposition]))
  end

  defp assign_proposition(conn, _opts) do
    case conn.params do
      %{"proposition_id" => proposition_id} ->
        proposition = Repo.get(Odfi.Proposition, proposition_id)
        assign(conn, :proposition, proposition)
      _ ->
        conn
    end
  end
end

web/views/option_view.ex
defmodule Odfi.OptionView do
  use Odfi.Web, :view
end

web/templates/option/edit.html.eex
<h2>Edit option</h2>

<%= render "form.html", changeset: @changeset,
                        action: proposition_option_path(@conn, :update, @proposition, @option) %>

<%= link "Back", to: proposition_option_path(@conn, :index, @proposition) %>

web/templates/option/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/option/index.html.eex
<h2>Listing options</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Proposition</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for option <- @options do %>
    <tr>
      <td><%= option.name %></td>
      <td><%= option.proposition_id %></td>

      <td class="text-right">
        <%= link "Show", to: proposition_option_path(@conn, :show, @proposition, option), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: proposition_option_path(@conn, :edit, @proposition, option), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: proposition_option_path(@conn, :delete, @proposition, option), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New option", to: proposition_option_path(@conn, :new, @proposition) %>
<%= link "Back", to: proposition_path(@conn, :show, @proposition) %>

web/templates/option/new.html.eex
<h2>New option</h2>

<%= render "form.html", changeset: @changeset,
                        action: proposition_option_path(@conn, :create, @proposition) %>

<%= link "Back", to: proposition_option_path(@conn, :index, @proposition) %>

web/templates/option/show.html.eex
<h2>Show option</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @option.name %>
  </li>

  <li>
    <strong>Proposition:</strong>
    <%= @option.proposition_id %>
  </li>

</ul>

<%= link "Edit", to: proposition_option_path(@conn, :edit, @proposition, @option) %>
<%= link "Back", to: proposition_option_path(@conn, :index, @proposition) %>