web/router.ex
defmodule Odfi.Router do
  use Odfi.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Odfi do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/propositions", PropositionController do
      resources "/options", OptionController
    end
    resources "/votes", VoteController

  end

  # Other scopes may use custom stacks.
  scope "/api", Odfi do
    pipe_through :api
    get "/propositions", PropositionController, :propositions
    get "/results/:id", VoteController, :results
    post "/vote", VoteController, :vote
  end
end

web/models/proposition.ex
defmodule Odfi.Proposition do
  use Odfi.Web, :model

  @derive {Poison.Encoder, only: [:name, :description, :options, :votes]}
  schema "propositions" do
    field :name, :string
    field :description, :string
    has_many :options, Odfi.Option
    has_many :votes, Odfi.Vote
    belongs_to :user, Odfi.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :description])
    |> validate_required([:name, :description])
  end
end

web/controllers/proposition_controller.ex
defmodule Odfi.PropositionController do
  use Odfi.Web, :controller

  alias Odfi.Proposition

  def index(conn, _params) do
    propositions = Repo.all(Proposition)
    render(conn, "index.html", propositions: propositions)
  end

  def propositions(conn, _params) do
    propositions = Repo.all from p in Proposition, preload: [:options]
    render(conn, "index.json", propositions: propositions)
  end

  def new(conn, _params) do
    changeset = Proposition.changeset(%Proposition{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"proposition" => proposition_params}) do
    changeset = Proposition.changeset(%Proposition{}, proposition_params)

    case Repo.insert(changeset) do
      {:ok, _proposition} ->
        conn
        |> put_flash(:info, "Proposition created successfully.")
        |> redirect(to: proposition_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    proposition = Repo.get!(Proposition, id)
    render(conn, "show.html", proposition: proposition)
  end

  def edit(conn, %{"id" => id}) do
    proposition = Repo.get!(Proposition, id)
    changeset = Proposition.changeset(proposition)
    render(conn, "edit.html", proposition: proposition, changeset: changeset)
  end

  def update(conn, %{"id" => id, "proposition" => proposition_params}) do
    proposition = Repo.get!(Proposition, id)
    changeset = Proposition.changeset(proposition, proposition_params)

    case Repo.update(changeset) do
      {:ok, proposition} ->
        conn
        |> put_flash(:info, "Proposition updated successfully.")
        |> redirect(to: proposition_path(conn, :show, proposition))
      {:error, changeset} ->
        render(conn, "edit.html", proposition: proposition, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    proposition = Repo.get!(Proposition, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(proposition)

    conn
    |> put_flash(:info, "Proposition deleted successfully.")
    |> redirect(to: proposition_path(conn, :index))
  end
end

web/views/proposition_view.ex
defmodule Odfi.PropositionView do
  use Odfi.Web, :view

  def render("index.json", %{propositions: propositions}) do
    Enum.map(propositions, fn proposition -> %{
      id: proposition.id,
      name: proposition.name,
      description: proposition.description,
      options: Enum.map(proposition.options, fn option -> %{id: option.id, name: option.name} end)
    } end )
  end
end

web/templates/proposition/edit.html.eex
<h2>Edit proposition</h2>

<%= render "form.html", changeset: @changeset,
                        action: proposition_path(@conn, :update, @proposition) %>

<%= link "Back", to: proposition_path(@conn, :index) %>

web/templates/proposition/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/proposition/index.html.eex
<h2>Listing propositions</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for proposition <- @propositions do %>
    <tr>
      <td><%= proposition.name %></td>
      <td><%= proposition.description %></td>
      <td><%= proposition.user_id %></td>

      <td class="text-right">
        <%= link "Show", to: proposition_path(@conn, :show, proposition), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: proposition_path(@conn, :edit, proposition), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: proposition_path(@conn, :delete, proposition), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New proposition", to: proposition_path(@conn, :new) %>
<%= link "Back", to: page_path(@conn, :index) %>

web/templates/proposition/new.html.eex
<h2>New proposition</h2>

<%= render "form.html", changeset: @changeset,
                        action: proposition_path(@conn, :create) %>

<%= link "Back", to: proposition_path(@conn, :index) %>

web/templates/proposition/show.html.eex
<h2>Show proposition</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @proposition.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @proposition.description %>
  </li>

  <li>
    <strong>User:</strong>
    <%= @proposition.user_id %>
  </li>

</ul>

<%= link "Options", to: proposition_option_path(@conn, :index, @proposition) %>
<%= link "Edit", to: proposition_path(@conn, :edit, @proposition) %>
<%= link "Back", to: proposition_path(@conn, :index) %>